storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

middlewares:
  static-access-token:
    enabled: true
    staticAccessTokens:
      - key: my-super-secret-key
        user: verdaccio-user
        readonly: true
      - key: my-super-secret-key-with-write-perms
        user: verdaccio-user
        readonly: false

# You still need an auth plugin. For example, the default one:
auth:
  htpasswd:
    file: ./htpasswd

packages:
  '@*/*':
    access: $all
    publish: verdaccio-user
    unpublish: verdaccio-user
    proxy: npmjs

  '**':
    access: $all
    publish: verdaccio-user
    unpublish: verdaccio-user
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: http }